comment_width = 100
condense_wildcard_suffixes = true
error_on_line_overflow = true
error_on_unformatted = true
format_strings = true
imports_indent = "Block"
imports_layout = "Mixed"
max_width = 100
merge_imports = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
# report_todo = "Unnumbered"
required_version = "0.7.0"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
