language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
sudo: false
install:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo test --all --verbose
  - cargo test --lib --no-default-features --features 3D,use_rand --verbose
