language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
sudo: false
install:
  - test "${TRAVIS_RUST_VERSION//./_}" != "nightly" || rustup component add rustfmt-preview
script:
  - test "${TRAVIS_RUST_VERSION//./_}" != "nightly" || cargo fmt --all -- --check
  - cargo build --verbose
  - cargo test --tests --verbose
  - cargo test --lib --no-default-features --features 3D --verbose
