[package]
name = "ku-web"
version = "0.1.0"
authors = ["Alex Hamilton <alex.hamilton@ou.edu>"]

[dependencies]
stdweb = "0.4.6"
ku = { default-features = false, features = ["2D", "ui", "use_stdweb"], path = ".." }

[features]
default = []
light_ui = []
allow_incorrect = []
